### ISSUE TITLE
Failed to resolve v1.1.0 from jitpack.io

### ISSUE THREAD

**Issue by bam-e22** [lincollincol/compose-audiowaveform#11]
Failed to resolve: com.github.lincollincol:compose-audiowaveform:1.1.0
![image](https://user-images.githubusercontent.com/23008504/220609126-dd0a89a2-0576-4fb9-bdc7-9bff27224c15.png)

Could you please fix it help me? thanks!

**Comment by lincollincol** [comment]
Hello! Thank you for this bug report.
This issue should be fixed in v1.1.1
`implementation 'com.github.lincollincol:compose-audiowaveform:v1.1.1'`
